export { ReactComponent as IconLogo } from './icon-logo.svg';
export { ReactComponent as IconFacebook } from './icon-facebook.svg';
export { ReactComponent as IconGoogle } from './icon-google.svg';
export { ReactComponent as IconKakaotalk } from './icon-kakaotalk.svg';
export { ReactComponent as IconLine } from './icon-line.svg';
export { ReactComponent as IconNaver } from './icon-naver.svg';
export { ReactComponent as IconYoutube } from './icon-youtube.svg';
export { ReactComponent as Iconyoutube1 } from './icon-youtube.svg';
export { ReactComponent as IconTwitter } from './icon-twitter.svg';
